version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: qb-backend
    env_file:
      - .env
    volumes:
      - .:/app
      - maven-cache:/root/.m2
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    networks:
      - qb-network
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: qb-mysql
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - qb-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  maven-cache:
  mysql-data:

networks:
  qb-network:
    external: true
