FROM openjdk:21-jdk-slim

WORKDIR /app

# Install Maven
RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*

# Copy everything
COPY . .

# Build the app
RUN mvn clean package -DskipTests

# Run the app
CMD ["java", "-jar", "target/GabartiScholars-QB-BE-0.0.1-SNAPSHOT.jar"]